# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajZc1Bf34rFhEKZ9XP3OP6Xso439GJ9G
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('movies_metadata.csv')

df.head()

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()
df= df.drop_duplicates().reset_index(drop=True)

df = df[['title','overview','genres','tagline','vote_average','popularity']]

df

df = df.dropna(subset=['title'])
df['overview']=df['overview'].fillna("")
df.iloc[0]['genres']

import ast
df['genres']= df['genres'].apply (lambda x:"".join(i['name']for i in ast.literal_eval(x)))

df['tagline']=df['tagline'].fillna("")

df['tags'] = df['overview']+""+df['genres']+""+df['tagline']

df.head()

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words ]
    return"".join(words)

df['tags'] = df['tags'].apply(preprocess_text)

df.head()
df.tags[0]